# ANSIBLE ROLE
# By making roles, you can reuse them across multiple playbooks and projects, keeping your automation cleaner and more modular.
# You create a role once (e.g., "Install Jenkins") and use it in many playbooks, saving time and effort.

# Save the roles content (all the folders) in /etc/ansible/roles directory
# Modify the ansible configuration file & add the roles_path in it
# sudo echo "roles_path    = /etc/ansible/roles" >> /etc/ansible/ansible.cfg

# Ansible roles directory can be setup manually or automatically
# cd /etc/ansible/roles
# use ansible-galaxy init <role-name> to setup the files & folders automatically (here '<role-name>' is 'jenkins-setup')

# vi jenkins-role.yaml
---
- name: Installing Jenkins using Ansible Roles
  hosts: webservers
  become: true
  roles:
    - jenkins-setup
...

# Place the role in your "roles" directory, and run the playbook with:
# ansible-playbook -i inventory jenkins-playbook.yml

# Set the ansible roles path in ansible configuration file 
