# Create a user playbook

# vi user.yaml
---
- name: create a user
  hosts: all
  become: true
  tasks:
   - name: create user
     user:
        name: alexa
...

# ansible-playbook user.yaml
# verify if users are created in the nodes using “cat /etc/passwd”
