# SETUP WEB APP ONLY IN THE WEBSERVERS

# vi webapp.yaml
---
- name: Setup Web Application
  hosts: webservers
  become: true
  tasks:
    - name: Install Git
      package:
        name: git
        state: present

    - name: Install HTTPD or Apache2
      package:
        name: "{{ 'httpd' if ansible_distribution == 'Amazon' else 'apache2' }}"
        state: present

    - name: Start HTTPD or Apache2 service
      service:
        name: "{{ 'httpd' if ansible_distribution == 'Amazon' else 'apache2' }}"
        state: started
        enabled: true

    - name: Clone GitHub repository
      git:
        repo: https://github.com/pandacloud1/webapp2.git
        dest: /tmp/webapp2
        clone: yes
        update: yes

    - name: Copy files from webapp2 to /var/www/html using rsync
      command: >
        rsync -avz /tmp/webapp2/ /var/www/html/        # avz: archive verbose compress (used to transfer files by preserving its properties)
...

# ansible-playbook webapp.yaml
# Open the public IP of your webservers group (i.e., Node1) in the browser & check if the application is accessible
